(define (make-monitored fun)
  (let ((count_ 0))
    (lambda (input)
      (cond ((eq? input 'how-many-calls?)
             count_)
            ((eq? input 'reset-count)
             (set! count_ 0))
            (else
             (set! count_ (+ 1 count_))
             (fun input))))))
(define s (make-monitored sqrt))
(s 100)
(s 'how-many-calls?)
(s 9)
(s 'how-many-calls?)
(s 'reset-count)
(s 'how-many-calls?)