(define (test-code)
  (define d (make-deque))
  (display (empty-deque? d))(newline)
  (display (front-insert-deque! d 'foo))(newline)
  (display (front-insert-deque! d 'xixi))(newline)
  (display (rear-insert-deque! d 'schbsb))(newline)
  (display (front-insert-deque! d 'xi))(newline)
  (display (rear-insert-deque! d '0903))(newline)
  (display (front-delete-deque! d))(newline)
  (display (front-delete-deque! d))(newline)
  (display (front-delete-deque! d))(newline)
  (display (front-delete-deque! d))(newline)
  (display (front-delete-deque! d))(newline)
  ;(display (front-delete-deque! d))(newline);;empty deque
  'done)