(load "d:\\sicp\\chapter3\\put-get.ss")
(put_ 'se 'sch 250)
(put_ 'se 'hcs 99)
(put_ 'cs 'xixi 1000)
(put_ 'se 'sch 666)
(put_ 'proc 'add +)
(put_ 'proc 'negate (lambda (x) (- x)))
(display (get_ 'se 'sch))(newline)
(display (get_ 'se 'hcs))(newline)
((get_ 'proc 'add) 1 2)
((get_ 'proc 'negate) 2)
(display (get_ 'se 'hcshhh))