(define t2 (make-table))
(put 'se 'sch 250 t2)
(put 'se 'hcs 99 t2)
(put 'cs 'xixi 1000 t2)
(put 'se 'sch 666 t2)
(put 'proc 'add + t2)
(put 'proc 'negate (lambda (x) (- x)) t2)
(display t2)(newline)
(display (get 'se 'sch t2))(newline)
(display (get 'se 'hcs t2))(newline)
((get 'proc 'add t2) 1 2)
((get 'proc 'negate t2) 2)
(display (get 'se 'hcshhh t2))