;a)
'(and (supervisor ?person (Ben Bitdiddle))
      (address ?person ?where))
;b)
'(and (salary Ben-Bitdiddle ?Ben-salary)
      (salary ?preson ?others-salary)
      (lisp-value < ?other-salary Ben-salary))
;c)
'(and (not (job ?person (computer . ?type)))
      (supervisor ?person ?sv)
      (job ?person ?jb))